import Phaser from 'phaser';
import './style.css';
import charactersJson from './data/characters.json';
import enemiesJson from './data/enemies.json';
import bannersJson from './data/banners.json';
import worldsJson from './data/worlds.json';
import classesJson from './data/classes.json';
import type { CharacterData, EnemyData, BannerData, WorldData, ClassId } from './data/types';

const characters = charactersJson as CharacterData[];
const enemies = enemiesJson as EnemyData[];
const banners = bannersJson as BannerData[];
const worlds = worldsJson as WorldData[];
const classes = classesJson as {id:ClassId;name:string;strongAgainst:ClassId|null;icon:string}[];
const classMap = new Map(classes.map(c => [c.id, c]));
const charMap = new Map(characters.map(c => [c.id, c]));

interface UnitInstance { uid:string; characterId:string; level:number; xp:number; locked:boolean; favorite:boolean; }
interface SaveDataV2 { version:2; tickets:number; fragments:number; units:UnitInstance[]; discovered:string[]; team:string[]; selectedBanner:number; }
const SAVE_KEY='argagacha-save-v2';
const oldKey='argagacha-save-v1';
const uid=()=>`u_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`;
function starterUnit(id:string,level=1):UnitInstance{return{uid:uid(),characterId:id,level,xp:0,locked:false,favorite:false};}
function defaultSave():SaveDataV2{
  const units=[starterUnit('caballero_mariposa',5),starterUnit('detective_lince',3),starterUnit('capitan_blaze',2)];
  return{version:2,tickets:12,fragments:0,units,discovered:units.map(u=>u.characterId),team:units.map(u=>u.uid),selectedBanner:0};
}
function loadSave():SaveDataV2{
  try{
    const current=JSON.parse(localStorage.getItem(SAVE_KEY)||'null');
    if(current?.version===2)return current;
    const old=JSON.parse(localStorage.getItem(oldKey)||'null');
    if(old?.owned){
      const units:UnitInstance[]=[];
      Object.entries(old.owned as Record<string,number>).forEach(([id,count])=>{for(let i=0;i<count;i++)units.push(starterUnit(id));});
      const selected=(old.team as string[]||[]).map(id=>units.find(u=>u.characterId===id)?.uid).filter(Boolean) as string[];
      const migrated:SaveDataV2={version:2,tickets:old.tickets??12,fragments:old.fragments??0,units,discovered:[...new Set(units.map(u=>u.characterId))],team:selected.slice(0,3),selectedBanner:0};
      localStorage.setItem(SAVE_KEY,JSON.stringify(migrated));return migrated;
    }
  }catch{}
  return defaultSave();
}
function saveGame(s:SaveDataV2){localStorage.setItem(SAVE_KEY,JSON.stringify(s));}
const path=(p:string)=>`${import.meta.env.BASE_URL}${p}`;
const star=(n:number)=>'★'.repeat(n);

interface BattleUnit {data:CharacterData|EnemyData; hp:number; maxHp:number; sprite:Phaser.GameObjects.Image; x:number;y:number; bar:Phaser.GameObjects.Graphics; label:Phaser.GameObjects.Text;}

type Screen='home'|'gacha'|'summon'|'codex'|'units'|'team'|'detail'|'expeditions'|'battle';
class MainScene extends Phaser.Scene{
  save=loadSave(); screen:Screen='home'; summonQueue:CharacterData[]=[]; summonIndex=0; selectedExpedition=0;
  constructor(){super('main');}
  preload(){
    this.load.image('logo',path('assets/ui/logo.png'));this.load.image('ticket',path('assets/ui/ticketgacha.png'));this.load.image('fragment',path('assets/ui/fragmentos.png'));
    worlds.forEach(w=>{this.load.image(`bg-${w.id}`,path(w.background));this.load.image(`world-banner-${w.id}`,path(w.bannerImage));});
    banners.forEach(b=>this.load.image(`banner-${b.id}`,path(b.image)));
    classes.forEach(c=>this.load.image(`class-${c.id}`,path(c.icon)));
    characters.forEach(c=>{this.load.image(`portrait-${c.id}`,path(c.portrait));this.load.image(`char-${c.id}`,path(c.sprite));});
    enemies.forEach(e=>this.load.image(`enemy-${e.id}`,path(e.sprite)));
  }
  create(){this.renderHome();}
  clear(){this.tweens.killAll();this.children.removeAll();}
  txt(x:number,y:number,t:string,size=24,origin=.5,width=1000){return this.add.text(x,y,t,{fontFamily:'Arial, sans-serif',fontSize:`${size}px`,color:'#f8fbff',stroke:'#07101f',strokeThickness:5,align:'center',wordWrap:{width}}).setOrigin(origin);}
  panel(x:number,y:number,w:number,h:number,alpha=.92,color=0x101a31){return this.add.rectangle(x,y,w,h,color,alpha).setStrokeStyle(2,0x7d91b6);}
  button(x:number,y:number,w:number,h:number,label:string,fn:()=>void,accent=0xf2c45f){const r=this.add.rectangle(x,y,w,h,0x17243f,.97).setStrokeStyle(3,accent).setInteractive({useHandCursor:true});const t=this.txt(x,y,label,22);r.on('pointerover',()=>r.setFillStyle(0x26395f));r.on('pointerout',()=>r.setFillStyle(0x17243f));r.on('pointerdown',fn);return{r,t};}
  header(title='ARGAGACHA'){this.add.rectangle(640,38,1280,76,0x07101f,.95);this.add.image(28,38,'ticket').setDisplaySize(34,34).setOrigin(0,.5);this.txt(70,38,String(this.save.tickets),22,0);this.add.image(160,38,'fragment').setDisplaySize(34,34).setOrigin(0,.5);this.txt(202,38,String(this.save.fragments),22,0);this.txt(1240,38,title,18,1);}
  nav(active:Screen){const items:[Screen,string,()=>void][]=[['home','INICIO',()=>this.renderHome()],['gacha','GACHA',()=>this.renderGacha()],['units','UNIDADES',()=>this.renderUnits()],['team','EQUIPO',()=>this.renderTeam()],['codex','CÓDICE',()=>this.renderCodex()],['expeditions','EXPLORAR',()=>this.renderExpeditions()]];this.add.rectangle(640,690,1280,60,0x07101f,.98);items.forEach((it,i)=>{const x=110+i*212;const c=active===it[0]?0xf2c45f:0x8da0c4;const tx=this.txt(x,690,it[1],17);tx.setColor(active===it[0]?'#f2c45f':'#dce5f7').setInteractive({useHandCursor:true}).on('pointerdown',it[2]);this.add.rectangle(x,716,130,3,c);});}
  baseBackground(worldId='hoennia',tint=0x7b899e){this.add.image(640,360,`bg-${worldId}`).setDisplaySize(1280,720).setTint(tint);this.add.rectangle(640,360,1280,720,0x040914,.45);}

  renderHome(){this.screen='home';this.clear();this.baseBackground();this.header();this.add.image(640,150,'logo').setDisplaySize(310,190);this.txt(640,255,'Mundos distintos. Banners distintos. Una sola colección.',22);this.panel(640,435,780,280,.75);this.button(470,370,300,64,'INVOCAR',()=>this.renderGacha());this.button(810,370,300,64,'EXPEDICIONES',()=>this.renderExpeditions());this.button(470,465,300,64,'FORMAR EQUIPO',()=>this.renderTeam());this.button(810,465,300,64,'VER UNIDADES',()=>this.renderUnits());this.txt(640,555,'v0.2 · Renovación de interfaz y progreso por unidades',16);this.nav('home');}

  renderGacha(){this.screen='gacha';this.clear();const banner=banners[this.save.selectedBanner%banners.length];this.add.image(640,360,`banner-${banner.id}`).setDisplaySize(1280,720);this.add.rectangle(640,360,1280,720,0x030713,.24);this.header('PORTAL DE INVOCACIÓN');
    this.add.rectangle(640,610,1280,220,0x07101f,.88);this.txt(640,535,banner.name.toUpperCase(),35);this.txt(640,570,worlds.find(w=>w.id===banner.worldId)?.description||'',16,.5,850);
    const left=this.txt(55,330,'‹',72);left.setInteractive({useHandCursor:true}).on('pointerdown',()=>{this.save.selectedBanner=(this.save.selectedBanner-1+banners.length)%banners.length;saveGame(this.save);this.renderGacha();});
    const right=this.txt(1225,330,'›',72);right.setInteractive({useHandCursor:true}).on('pointerdown',()=>{this.save.selectedBanner=(this.save.selectedBanner+1)%banners.length;saveGame(this.save);this.renderGacha();});
    this.button(475,635,275,62,`1 TIRADA · ${banner.ticketCost} TICKET`,()=>this.pull(1));this.button(805,635,275,62,`10 TIRADAS · ${banner.ticketCost*10} TICKETS`,()=>this.pull(10));
    this.txt(640,470,`${star(5)} 5%  ·  ${star(4)} 15%  ·  ${star(3)} 30%  ·  ${star(2)} 50%`,17);this.nav('gacha');}
  pull(count:number){const banner=banners[this.save.selectedBanner%banners.length];const cost=banner.ticketCost*count;if(this.save.tickets<cost){this.toast('No tienes tickets suficientes.');return;}this.save.tickets-=cost;const results:CharacterData[]=[];for(let i=0;i<count;i++){const r=Math.random();let rarity=2,acc=0;for(const value of [5,4,3,2]){acc+=banner.rates[String(value)]||0;if(r<=acc){rarity=value;break;}}const pool=characters.filter(c=>c.bannerId===banner.id&&c.rarity===rarity);const c=Phaser.Utils.Array.GetRandom(pool.length?pool:characters.filter(x=>x.bannerId===banner.id));this.save.units.push(starterUnit(c.id));if(!this.save.discovered.includes(c.id))this.save.discovered.push(c.id);results.push(c);}saveGame(this.save);this.summonQueue=results;this.summonIndex=0;this.renderSummon();}
  renderSummon(showAll=false){this.screen='summon';this.clear();this.add.rectangle(640,360,1280,720,0x02050c);this.header('RESULTADOS DE INVOCACIÓN');if(showAll){this.txt(640,100,'RESULTADOS',34);const cols=this.summonQueue.length===1?1:5;this.summonQueue.forEach((c,i)=>{const x=this.summonQueue.length===1?640:160+(i%cols)*240;const y=this.summonQueue.length===1?340:220+Math.floor(i/cols)*250;this.drawUnitCard(x,y,c,190,210,true);});this.button(640,650,270,55,'CONTINUAR',()=>this.renderGacha());return;}
    const c=this.summonQueue[this.summonIndex];const glow=this.add.circle(640,340,210,c.rarity===5?0xffd65a:c.rarity===4?0xb37aff:0x68a7ff,.18);this.tweens.add({targets:glow,scale:1.25,alpha:.05,duration:900,yoyo:true,repeat:-1});const card=this.panel(640,335,440,500,.98,c.rarity===5?0x2b2211:0x101a31).setStrokeStyle(5,c.rarity===5?0xffd65a:c.rarity===4?0xb37aff:0x6f87b1);const p=this.add.image(640,300,`portrait-${c.id}`).setDisplaySize(360,360).setAlpha(0).setScale(.7);this.tweens.add({targets:p,alpha:1,scale:1,duration:420,ease:'Back.easeOut'});this.txt(640,525,c.name,32);this.txt(640,565,`${classMap.get(c.classId)?.name} · ${star(c.rarity)}`,23);this.txt(640,604,`Unidad nueva · Nivel 1`,17);this.txt(640,665,'PULSA PARA CONTINUAR',16);card.setInteractive({useHandCursor:true}).on('pointerdown',()=>{if(this.summonIndex<this.summonQueue.length-1){this.summonIndex++;this.renderSummon();}else this.renderGacha();});if(this.summonQueue.length>1)this.button(1090,665,220,48,'MOSTRAR TODO',()=>this.renderSummon(true));}

  drawUnitCard(x:number,y:number,c:CharacterData,w=190,h=210,showLevel=false,unit?:UnitInstance){const rarityColor=c.rarity===5?0xffd65a:c.rarity===4?0xb37aff:0x7f93b7;const r=this.add.rectangle(x,y,w,h,0x10192c,.98).setStrokeStyle(2,rarityColor).setInteractive({useHandCursor:true});this.add.image(x,y-32,`portrait-${c.id}`).setDisplaySize(w-16,h-68);this.add.rectangle(x,y+h/2-40,w,80,0x060a13,.9);this.add.image(x-w/2+24,y+h/2-53,`class-${c.classId}`).setDisplaySize(28,28);this.txt(x,y+h/2-55,c.name,16);this.txt(x,y+h/2-30,showLevel?`${star(c.rarity)} · Nv. ${unit?.level??1}`:star(c.rarity),14);return r;}
  renderUnits(){this.screen='units';this.clear();this.add.rectangle(640,360,1280,720,0x0a1222);this.header('MIS UNIDADES');this.txt(640,100,`UNIDADES · ${this.save.units.length}`,32);if(!this.save.units.length)this.txt(640,340,'No tienes unidades.',28);this.save.units.forEach((u,i)=>{const c=charMap.get(u.characterId)!;const x=135+(i%6)*205,y=215+Math.floor(i/6)*230;const card=this.drawUnitCard(x,y,c,170,195,true,u);card.on('pointerdown',()=>this.showUnit(u,'units'));if(u.favorite)this.txt(x+67,y-82,'♥',22);if(u.locked)this.txt(x-67,y-82,'🔒',16);});this.nav('units');}
  renderCodex(){this.screen='codex';this.clear();this.add.rectangle(640,360,1280,720,0x0a1222);this.header('CÓDICE MULTIVERSAL');this.txt(640,100,`HOENNIA · ${this.save.discovered.length}/${characters.length} descubiertos`,30);characters.forEach((c,i)=>{const known=this.save.discovered.includes(c.id);const x=135+(i%6)*205,y=215+Math.floor(i/6)*230;const r=this.add.rectangle(x,y,170,195,known?0x10192c:0x080d18,.98).setStrokeStyle(2,known?0x7f93b7:0x33405a).setInteractive({useHandCursor:known});if(known){this.add.image(x,y-32,`portrait-${c.id}`).setDisplaySize(154,127);this.add.rectangle(x,y+58,170,78,0x060a13,.92);this.txt(x,y+43,c.name,15);this.txt(x,y+68,star(c.rarity),14);r.on('pointerdown',()=>this.showCodexCharacter(c));}else{this.txt(x,y-10,'?',72);this.txt(x,y+62,'SIN DESCUBRIR',13);}});this.nav('codex');}
  showCodexCharacter(c:CharacterData){this.clear();this.add.rectangle(640,360,1280,720,0x0a1222);this.header('CÓDICE');this.add.image(315,390,`portrait-${c.id}`).setDisplaySize(500,500);this.add.rectangle(870,375,640,520,0x101a31,.94).setStrokeStyle(2,0x8194b7);this.add.image(610,165,`class-${c.classId}`).setDisplaySize(48,48);this.txt(870,150,c.name,37);this.txt(870,195,`${classMap.get(c.classId)?.name} · ${star(c.rarity)}`,20);this.add.text(590,245,c.lore,{fontFamily:'Arial',fontSize:'21px',color:'#eaf0ff',wordWrap:{width:560},lineSpacing:7});this.button(120,660,170,50,'VOLVER',()=>this.renderCodex());}
  showUnit(u:UnitInstance,back:'units'|'team'){const c=charMap.get(u.characterId)!;this.screen='detail';this.clear();this.add.rectangle(640,360,1280,720,0x0a1222);this.header('FICHA DE UNIDAD');this.add.image(300,390,`portrait-${c.id}`).setDisplaySize(520,520);const fade=this.add.rectangle(475,390,350,520,0x0a1222,.35);this.panel(870,370,650,530,.96);this.add.image(600,145,`class-${c.classId}`).setDisplaySize(50,50);this.txt(870,135,c.name,38);this.txt(870,182,`${classMap.get(c.classId)?.name} · ${star(c.rarity)} · Nv. ${u.level}`,21);this.add.text(590,230,c.lore,{fontFamily:'Arial',fontSize:'20px',color:'#eaf0ff',wordWrap:{width:560},lineSpacing:6});const mult=1+(u.level-1)*.06;this.txt(870,485,`PV ${Math.round(c.stats.hp*mult)}   ATQ ${Math.round(c.stats.attack*mult)}   DEF ${Math.round(c.stats.defense*mult)}   VEL ${c.stats.speed}`,19);this.button(725,555,230,48,u.favorite?'QUITAR FAVORITO':'MARCAR FAVORITO',()=>{u.favorite=!u.favorite;saveGame(this.save);this.showUnit(u,back);});this.button(1015,555,230,48,u.locked?'DESBLOQUEAR':'BLOQUEAR',()=>{u.locked=!u.locked;saveGame(this.save);this.showUnit(u,back);});if(!u.locked&&!this.save.team.includes(u.uid))this.button(870,615,300,48,'CONVERTIR EN FRAGMENTOS',()=>this.destroyUnit(u,back),0xe06d6d);this.button(120,660,170,50,'VOLVER',()=>back==='units'?this.renderUnits():this.renderTeam());}
  destroyUnit(u:UnitInstance,back:'units'|'team'){const c=charMap.get(u.characterId)!;this.save.units=this.save.units.filter(x=>x.uid!==u.uid);this.save.team=this.save.team.filter(id=>id!==u.uid);this.save.fragments+=c.rarity*10;saveGame(this.save);back==='units'?this.renderUnits():this.renderTeam();}

  renderTeam(){this.screen='team';this.clear();this.add.rectangle(640,360,1280,720,0x0a1222);this.header('FORMACIÓN');this.txt(640,100,'EQUIPO ACTUAL',31);for(let i=0;i<3;i++){const u=this.save.units.find(x=>x.uid===this.save.team[i]);const x=390+i*250,y=225;this.add.rectangle(x,y,200,210,0x10192c,.96).setStrokeStyle(3,u?0xf2c45f:0x44516d);if(u){const c=charMap.get(u.characterId)!;this.add.image(x,y-22,`portrait-${c.id}`).setDisplaySize(184,140);this.txt(x,y+62,c.name,16);this.txt(x,y+86,`Nv. ${u.level}`,14);}else this.txt(x,y,'HUECO VACÍO',17);}this.txt(640,375,'PULSA UNA UNIDAD PARA AÑADIRLA O QUITARLA',17);this.save.units.forEach((u,i)=>{const c=charMap.get(u.characterId)!;const selected=this.save.team.includes(u.uid);const x=120+(i%7)*175,y=485+Math.floor(i/7)*145;const r=this.add.rectangle(x,y,145,120,selected?0x29375b:0x10192c,.98).setStrokeStyle(2,selected?0xf2c45f:0x7082a4).setInteractive({useHandCursor:true});this.add.image(x-42,y,`portrait-${c.id}`).setDisplaySize(56,95);this.txt(x+24,y-22,c.name,13,.5,80);this.txt(x+24,y+13,`Nv. ${u.level}`,13);this.txt(x+24,y+38,selected?'EN EQUIPO':'DISPONIBLE',11);r.on('pointerdown',()=>{if(selected)this.save.team=this.save.team.filter(id=>id!==u.uid);else if(this.save.team.length<3)this.save.team.push(u.uid);else this.toast('El equipo ya tiene 3 unidades.');saveGame(this.save);this.renderTeam();});;});this.nav('team');}

  renderExpeditions(){this.screen='expeditions';this.clear();this.baseBackground();this.header('MAPA DE EXPEDICIONES');this.txt(640,105,'ELIGE UNA EXPEDICIÓN',34);const missions=[{name:'Sendero del Bosque',difficulty:'Fácil',enemies:2,reward:'1 ticket · 10 fragmentos'},{name:'Costa de Isla Mayo',difficulty:'Normal',enemies:3,reward:'2 tickets · 15 fragmentos'},{name:'Distrito Industrial',difficulty:'Difícil',enemies:3,reward:'3 tickets · 25 fragmentos'}];missions.forEach((m,i)=>{const y=220+i*125;const selected=this.selectedExpedition===i;const r=this.add.rectangle(640,y,760,100,selected?0x24385f:0x101a31,.94).setStrokeStyle(3,selected?0xf2c45f:0x7b8ead).setInteractive({useHandCursor:true});this.txt(350,y-18,m.name,24,0);this.txt(350,y+20,`${m.difficulty} · ${m.enemies} enemigos`,16,0);this.txt(920,y,m.reward,16);r.on('pointerdown',()=>{this.selectedExpedition=i;this.renderExpeditions();});});this.button(640,610,300,58,'INICIAR EXPEDICIÓN',()=>this.startBattle(this.selectedExpedition));this.nav('expeditions');}
  drawHp(u:BattleUnit){const pct=Phaser.Math.Clamp(u.hp/u.maxHp,0,1);u.bar.clear();u.bar.fillStyle(0x000000,.8).fillRoundedRect(u.x-82,u.y+69,164,18,5);u.bar.fillStyle(pct>.5?0x43c774:pct>.25?0xe0b54c:0xdc5b5b,1).fillRoundedRect(u.x-78,u.y+73,156*pct,10,4);u.label.setText(`${Math.max(0,u.hp)} / ${u.maxHp}`);}
  startBattle(mission=0){const selected=this.save.team.map(id=>this.save.units.find(u=>u.uid===id)).filter(Boolean) as UnitInstance[];if(!selected.length){this.toast('Forma un equipo primero.');this.renderTeam();return;}this.screen='battle';this.clear();this.baseBackground();this.header('EXPEDICIÓN');const foeCount=[2,3,3][mission];const foes=enemies.filter(e=>!e.boss).sort(()=>Math.random()-.5).slice(0,foeCount);const allies:BattleUnit[]=selected.map((u,i)=>{const c=charMap.get(u.characterId)!;const mult=1+(u.level-1)*.06;const max=Math.round(c.stats.hp*mult);const x=210,y=190+i*165;const sprite=this.add.image(x,y,`char-${c.id}`).setDisplaySize(150,150);const bar=this.add.graphics();const label=this.txt(x,y+95,'',13);return{data:{...c,stats:{...c.stats,attack:Math.round(c.stats.attack*mult),defense:Math.round(c.stats.defense*mult),hp:max}},hp:max,maxHp:max,sprite,x,y,bar,label};});const bads:BattleUnit[]=foes.map((e,i)=>{const scale=1+mission*.18;const max=Math.round(e.stats.hp*scale),x=1070,y=215+i*165;const sprite=this.add.image(x,y,`enemy-${e.id}`).setDisplaySize(150,150).setFlipX(true);const bar=this.add.graphics();const label=this.txt(x,y+95,'',13);return{data:{...e,stats:{...e.stats,attack:Math.round(e.stats.attack*scale),defense:Math.round(e.stats.defense*scale),hp:max}},hp:max,maxHp:max,sprite,x,y,bar,label};});[...allies,...bads].forEach(u=>this.drawHp(u));const log=this.add.text(420,540,'Preparados para combatir.',{fontFamily:'Arial',fontSize:'18px',color:'#fff',backgroundColor:'#000c',padding:{x:14,y:10},wordWrap:{width:440}});const start=this.button(640,645,300,50,'COMENZAR COMBATE',async()=>{start.r.disableInteractive();start.t.setText('COMBATE EN CURSO');let turn=0;while(allies.some(a=>a.hp>0)&&bads.some(b=>b.hp>0)&&turn<60){turn++;for(const a of allies.filter(x=>x.hp>0)){const target=bads.find(x=>x.hp>0);if(target)await this.attack(a,target,log);}for(const b of bads.filter(x=>x.hp>0)){const target=allies.find(x=>x.hp>0);if(target)await this.attack(b,target,log);}}const won=allies.some(a=>a.hp>0);const rewards=[{t:1,f:10},{t:2,f:15},{t:3,f:25}][mission];if(won){this.save.tickets+=rewards.t;this.save.fragments+=rewards.f;selected.forEach(u=>{u.xp+=20+mission*15;if(u.xp>=100){u.level++;u.xp-=100;}});saveGame(this.save);log.setText(`¡VICTORIA! +${rewards.t} tickets · +${rewards.f} fragmentos`);}else log.setText('DERROTA. Revisa la formación y vuelve a intentarlo.');this.button(640,645,300,50,'VOLVER AL MAPA',()=>this.renderExpeditions());});}
  async attack(attacker:BattleUnit,target:BattleUnit,log:Phaser.GameObjects.Text){const clsA=attacker.data.classId,clsT=target.data.classId;const advantage=classMap.get(clsA)?.strongAgainst===clsT?1.25:classMap.get(clsT)?.strongAgainst===clsA?0.8:1;const damage=Math.max(5,Math.round((attacker.data.stats.attack-target.data.stats.defense*.35)*advantage*(.9+Math.random()*.2)));log.setText(`${attacker.data.name} inflige ${damage}${advantage>1?' · ¡VENTAJA!':''}`);await new Promise<void>(resolve=>this.tweens.add({targets:attacker.sprite,x:attacker.x+(target.x>attacker.x?30:-30),duration:95,yoyo:true,onComplete:()=>resolve()}));target.hp-=damage;this.drawHp(target);this.tweens.add({targets:target.sprite,alpha:.25,duration:65,yoyo:true,repeat:1});if(target.hp<=0)this.tweens.add({targets:[target.sprite,target.bar,target.label],alpha:0,duration:260});await new Promise<void>(resolve=>this.time.delayedCall(160,()=>resolve()));}
  toast(message:string){const box=this.add.rectangle(640,90,520,54,0x060a13,.96).setStrokeStyle(2,0xf2c45f).setDepth(100);const t=this.txt(640,90,message,18).setDepth(101);this.tweens.add({targets:[box,t],alpha:0,delay:1500,duration:350,onComplete:()=>{box.destroy();t.destroy();}});}
}
new Phaser.Game({type:Phaser.AUTO,parent:'game',width:1280,height:720,backgroundColor:'#090d18',scene:[MainScene],scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH}});
